# Generated by Django 4.1.6 on 2023-04-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmotors', '0003_alter_acmotors_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='acmotors',
            name='enclosureOther',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='acmotors',
            name='fittedWithOther',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
