# Generated by Django 4.1.6 on 2023-04-28 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acmotors', '0004_acmotors_enclosureother_acmotors_fittedwithother'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acmotors',
            old_name='fittedwith',
            new_name='fittedWith',
        ),
    ]
