# Generated by Django 4.1.6 on 2023-05-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acmotors', '0008_remove_acmotorjobdetails_job_num_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acmotorjobdetails',
            old_name='pictues',
            new_name='pictures',
        ),
    ]
