# Generated by Django 4.1.6 on 2023-05-02 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acmotors', '0010_acmotorjobdetails_status_acmotorjobdetails_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcConditionAssesment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visual', models.BooleanField(default=False)),
                ('pictures', models.BooleanField(default=False)),
                ('missing', models.BooleanField(default=False)),
                ('broken', models.BooleanField(default=False)),
                ('electrical', models.BooleanField(default=False)),
                ('insulation', models.BooleanField(default=False)),
                ('winding', models.BooleanField(default=False)),
                ('turn', models.BooleanField(default=False)),
                ('auxiliary', models.BooleanField(default=False)),
                ('heater', models.BooleanField(default=False)),
                ('job', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='acmotors.acmotorjobdetails')),
            ],
        ),
    ]
