# Generated by Django 4.1.6 on 2023-05-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmotors', '0013_acdismantleinspection_dismantle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acmotorjobdetails',
            name='app_other',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='acmotorjobdetails',
            name='specificDate',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
