# Generated by Django 4.1.6 on 2023-05-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmotors', '0018_comments_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='acmotors',
            name='hpkwValue',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
