# Generated by Django 4.1.6 on 2023-05-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmotors', '0025_acmotorjobdetails_eyeboltdamaged'),
    ]

    operations = [
        migrations.AddField(
            model_name='acconditionassessment',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='acdismantleinspection',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
