# Generated by Django 4.1.6 on 2023-04-28 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('Phone', models.CharField(max_length=20)),
            ],
        ),
    ]
