from django.db import models
import uuid
from customer.models import Customer

class ACMotors(models.Model):
    id = models.CharField(primary_key=True,editable=False,default=uuid.uuid4, max_length=255) 
    manufacturer = models.CharField(blank=True, max_length=250)
    serial = models.CharField(blank=True, max_length=250)
    model = models.CharField(blank=True, max_length=250)
    rpm = models.CharField(blank=True, max_length=250)
    frame =  models.CharField(blank=True, max_length=250)
    hpkw = models.CharField(blank=True, max_length=250)
    volts = models.CharField(blank=True, max_length=250)
    amps = models.CharField(blank=True, max_length=250)
    phase = models.CharField(blank=True, max_length=250)
    _class = models.CharField(blank=True, max_length=250)
    ambTemp = models.CharField(blank= True, max_length=250)
    timeRating = models.CharField(blank=True, max_length=250)
    div = models.CharField(blank=True, max_length=250)
    enclosure = models.CharField(blank=True, max_length=250)
    eyebolt = models.CharField(blank=True, max_length=250)
    fittedWith = models.CharField(blank=True, max_length=250)
    inOut = models.CharField(blank=True, max_length=250)
    measurement = models.CharField(blank=True, max_length=250)
    cycles = models.CharField(blank=True, max_length=250,default='')
    enclosureOther = models.CharField(blank=True, max_length=250, default='')
    fittedWithOther = models.CharField(blank=True, max_length=250, default='')


class ACMotorJobDetails(models.Model):
    id = models.AutoField(primary_key=True)
    customer = models.ForeignKey(Customer, related_name="job", on_delete=models.PROTECT, default=None)
    motor = models.ForeignKey(ACMotors, related_name="motor", on_delete=models.PROTECT, default=None)
    specificDate = models.CharField(max_length=250,default='',null=True)
    equipment = models.CharField(blank=True, max_length=250)
    application = models.CharField(blank=True, max_length=250)
    urgency = models.CharField(blank=True, max_length=250)
    quote = models.CharField(blank=True, max_length=250)
    po_num = models.CharField(blank=True, max_length=250)
    customerComments = models.CharField(blank=True, max_length=1000)
    partsMissing = models.CharField(blank=True, max_length=1000)
    pictures = models.CharField(blank=True, max_length=250, default='')
    signature = models.CharField(blank=True, max_length=250, default='')
    date = models.DateTimeField(auto_now_add=True)
    app_other = models.CharField(null=True, max_length=250, default='')
    status = models.CharField(blank=True, max_length=250, default="")
    step = models.CharField(blank=True, max_length=250, default="")

class AcConditionAssessment(models.Model):
    id = models.AutoField(primary_key=True)
    job = models.ForeignKey(ACMotorJobDetails, related_name="condition", on_delete=models.CASCADE, default=None)
    visual = models.BooleanField(default=False)
    pictures = models.BooleanField(default=False)
    missing = models.BooleanField(default=False)
    broken = models.BooleanField(default=False)
    electrical = models.BooleanField(default=False)
    insulation = models.BooleanField(default=False)
    winding = models.BooleanField(default=False)
    turn = models.BooleanField(default=False)
    auxiliary = models.BooleanField(default=False)
    heater = models.BooleanField(default=False)

class AcDismantleInspection(models.Model):
    id = models.AutoField(primary_key=True)
    job = models.ForeignKey(ACMotorJobDetails, related_name="dismantle", on_delete=models.CASCADE, default=None)
    dismantle = models.BooleanField(default=False)
    pictures = models.BooleanField(default=False)
    mechanical = models.BooleanField(default=False)
    bearings = models.BooleanField(default=False)
    oil = models.BooleanField(default=False)
    mechFit = models.BooleanField(default=False)
    failure = models.BooleanField(default=False)
    electrical = models.BooleanField(default=False)
    insulation = models.BooleanField(default=False)
    winding = models.BooleanField(default=False)
    surge = models.BooleanField(default=False)
    recordData = models.BooleanField(default=False)

class Comments(models.Model):
    id = models.AutoField(primary_key=True)
    job = models.ForeignKey(ACMotorJobDetails, related_name="comments", on_delete=models.CASCADE, default=None)
    comments = models.CharField(blank=True, max_length=10000)