# Generated by Django 4.1.6 on 2023-05-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmotors', '0005_rename_fittedwith_acmotors_fittedwith'),
    ]

    operations = [
        migrations.AddField(
            model_name='acmotorjobdetails',
            name='specificDate',
            field=models.CharField(default='', max_length=250),
        ),
    ]
