# Generated by Django 4.1.6 on 2023-05-01 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_phone_customer_address_and_more'),
        ('acmotors', '0007_alter_acmotorjobdetails_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acmotorjobdetails',
            name='job_num',
        ),
        migrations.AddField(
            model_name='acmotorjobdetails',
            name='app_other',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='acmotorjobdetails',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='job', to='customer.customer'),
        ),
        migrations.AddField(
            model_name='acmotorjobdetails',
            name='motor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='motor', to='acmotors.acmotors'),
        ),
    ]
