# Generated by Django 4.1.6 on 2023-05-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmotors', '0009_rename_pictues_acmotorjobdetails_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='acmotorjobdetails',
            name='status',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='acmotorjobdetails',
            name='step',
            field=models.CharField(default='', max_length=250),
        ),
    ]
