# Generated by Django 4.1.6 on 2023-05-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmotors', '0012_acconditionassessment_acdismantleinspection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acdismantleinspection',
            name='dismantle',
            field=models.BooleanField(default=False),
        ),
    ]
