# Generated by Django 4.1.6 on 2023-05-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmotors', '0014_alter_acmotorjobdetails_app_other_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.CharField(blank=True, max_length=10000)),
            ],
        ),
        migrations.AlterField(
            model_name='acmotorjobdetails',
            name='application',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='acmotorjobdetails',
            name='equipment',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='acmotorjobdetails',
            name='pictures',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='acmotorjobdetails',
            name='po_num',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='acmotorjobdetails',
            name='quote',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='acmotorjobdetails',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='acmotorjobdetails',
            name='status',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='acmotorjobdetails',
            name='step',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='acmotorjobdetails',
            name='urgency',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='acmotors',
            name='_class',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='acmotors',
            name='ambTemp',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='acmotors',
            name='amps',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='acmotors',
            name='cycles',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='acmotors',
            name='div',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='acmotors',
            name='enclosure',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='acmotors',
            name='eyebolt',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='acmotors',
            name='fittedWith',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='acmotors',
            name='frame',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='acmotors',
            name='hpkw',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='acmotors',
            name='inOut',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='acmotors',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='acmotors',
            name='measurement',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='acmotors',
            name='model',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='acmotors',
            name='phase',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='acmotors',
            name='rpm',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='acmotors',
            name='serial',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='acmotors',
            name='timeRating',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='acmotors',
            name='volts',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
