# Generated by Django 4.1.6 on 2023-05-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmotors', '0020_alter_acmotors__class_alter_acmotors_ambtemp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acmotorjobdetails',
            name='application',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='acmotorjobdetails',
            name='customerComments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='acmotorjobdetails',
            name='equipment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='acmotorjobdetails',
            name='partsMissing',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='acmotorjobdetails',
            name='pictures',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='acmotorjobdetails',
            name='po_num',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='acmotorjobdetails',
            name='quote',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='acmotorjobdetails',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='acmotorjobdetails',
            name='status',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='acmotorjobdetails',
            name='step',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='acmotorjobdetails',
            name='urgency',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
