# Generated by Django 4.1.6 on 2023-05-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmotors', '0022_acconditionassessment_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acmotors',
            name='eyeboltDamaged',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
