# Generated by Django 4.1.6 on 2023-05-05 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acmotors', '0023_acmotors_eyeboltdamaged'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acmotors',
            name='eyeboltDamaged',
        ),
    ]
