# Generated by Django 4.1.6 on 2023-05-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acmotors', '0024_remove_acmotors_eyeboltdamaged'),
    ]

    operations = [
        migrations.AddField(
            model_name='acmotorjobdetails',
            name='eyeboltDamaged',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
